### ISSUE TITLE
Project seems no longer compiles on Xcode Version 15.0 beta 2 (15A5161b) and iOS 17 Simulator

### ISSUE THREAD

**Issue by waelsaad** [SwiftUI-Plus/Connections#1]
Hi :) This project seems no longer compiles on Xcode Version 15.0 beta 2 (15A5161b) and iOS 17 Simulator. Thanks

**Comment by shaps80** [comment]
Can you show a screenshot, detailed error, etc.
This will enable me to respond and/or fix more quickly.

Thanks for raising though, obvs Xcode 15 (more likely a Swift 5.9 related issue) is beta atm so its not totally unexpected 👍

**Comment by shaps80** [comment]
This is now resolved @waelsaad in `v1.1.1`

**Comment by waelsaad** [comment]
Perfect. Thank you.

**Comment by waelsaad** [comment]
Oh @shaps80 might be a silly question but where is v1.1.1?

**Comment by waelsaad** [comment]
Hey @shaps80 I got v1.1.1 using SPM but I think the issue is still there.
<img width="1231" alt="Screenshot 2023-07-13 at 9 12 49 am" src="https://github.com/SwiftUI-Plus/Connections/assets/4057766/27b09b46-1dfc-4bf1-a7cd-3fb0240c60af">

**Comment by shaps80** [comment]
@waelsaad sorry I meant`1.2.0`
